/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_Vista;

import com.sun.glass.events.KeyEvent;

/**
 *
 * @author alumno
 */
public class Ventana_Partida_normal extends javax.swing.JFrame {

    /**
     * Creates new form Ventana_Partida
     */
    public Ventana_Partida_normal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_Ventana_Actual = new javax.swing.JLabel();
        jLabel_ContadorTiempo = new javax.swing.JLabel();
        jLabel_ContadorPuntuacion = new javax.swing.JLabel();
        jLabel_ContadorFallos = new javax.swing.JLabel();
        jButton_Start = new javax.swing.JButton();
        JLabel_Operacion = new javax.swing.JLabel();
        jTextField_Respuesta = new javax.swing.JTextField();
        jButton_Cerrar = new javax.swing.JButton();
        jButton_Volver = new javax.swing.JButton();
        jButton_Enter = new javax.swing.JButton();
        jLabel_LogAs = new javax.swing.JLabel();
        jLabel_Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_Ventana_Actual.setFont(new java.awt.Font("Digital Dare", 1, 24)); // NOI18N
        jLabel_Ventana_Actual.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Ventana_Actual.setText("RANDOM.MATHS");
        getContentPane().add(jLabel_Ventana_Actual, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel_ContadorTiempo.setFont(new java.awt.Font("Digital Dare", 0, 95)); // NOI18N
        jLabel_ContadorTiempo.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_ContadorTiempo.setText("59");
        getContentPane().add(jLabel_ContadorTiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 90, 150, 90));

        jLabel_ContadorPuntuacion.setFont(new java.awt.Font("Digital Dare", 1, 60)); // NOI18N
        jLabel_ContadorPuntuacion.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_ContadorPuntuacion.setText("0");
        getContentPane().add(jLabel_ContadorPuntuacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 420, -1, -1));

        jLabel_ContadorFallos.setFont(new java.awt.Font("Digital Dare", 1, 60)); // NOI18N
        jLabel_ContadorFallos.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_ContadorFallos.setText("0");
        getContentPane().add(jLabel_ContadorFallos, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 420, -1, -1));

        jButton_Start.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton_start.png"))); // NOI18N
        jButton_Start.setPreferredSize(new java.awt.Dimension(310, 90));
        getContentPane().add(jButton_Start, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 660, 240, 70));

        JLabel_Operacion.setFont(new java.awt.Font("Digital Dare", 0, 60)); // NOI18N
        JLabel_Operacion.setForeground(new java.awt.Color(255, 255, 255));
        JLabel_Operacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabel_Operacion.setText("123+123");
        getContentPane().add(JLabel_Operacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, 600, -1));

        jTextField_Respuesta.setFont(new java.awt.Font("Digital Dare", 0, 48)); // NOI18N
        getContentPane().add(jTextField_Respuesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 420, 530, 80));

        jButton_Cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Icon.png"))); // NOI18N
        jButton_Cerrar.setPreferredSize(new java.awt.Dimension(45, 27));
        getContentPane().add(jButton_Cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 10, -1, -1));

        jButton_Volver.setIcon(new javax.swing.ImageIcon("C:\\Users\\Equipo\\Documents\\NetBeansProjects\\proyecto_programacion\\src\\imagenes\\volver_normal.png")); // NOI18N
        getContentPane().add(jButton_Volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 530, 240, 70));

        jButton_Enter.setIcon(new javax.swing.ImageIcon("C:\\Users\\Equipo\\Documents\\NetBeansProjects\\proyecto_programacion\\src\\imagenes\\intro.png")); // NOI18N
        getContentPane().add(jButton_Enter, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 530, 240, 70));

        jLabel_LogAs.setFont(new java.awt.Font("Digital Dare", 1, 24)); // NOI18N
        jLabel_LogAs.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_LogAs.setText("LOG: ");
        getContentPane().add(jLabel_LogAs, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 740, 460, -1));

        jLabel_Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Fondo.png"))); // NOI18N
        getContentPane().add(jLabel_Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 780));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana_Partida_normal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana_Partida_normal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana_Partida_normal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana_Partida_normal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana_Partida_normal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel JLabel_Operacion;
    public javax.swing.JButton jButton_Cerrar;
    public javax.swing.JButton jButton_Enter;
    public javax.swing.JButton jButton_Start;
    public javax.swing.JButton jButton_Volver;
    private javax.swing.JLabel jLabel_ContadorFallos;
    public javax.swing.JLabel jLabel_ContadorPuntuacion;
    public javax.swing.JLabel jLabel_ContadorTiempo;
    private javax.swing.JLabel jLabel_Fondo;
    public javax.swing.JLabel jLabel_LogAs;
    private javax.swing.JLabel jLabel_Ventana_Actual;
    public javax.swing.JTextField jTextField_Respuesta;
    // End of variables declaration//GEN-END:variables
}
