/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_Vista;

import com.sun.glass.events.KeyEvent;

/**
 *
 * @author Pedro
 */
public class Ventana_Ranking extends javax.swing.JFrame {

    /**
     * Creates new form Ventana_Ranking
     */
    public Ventana_Ranking() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_modo = new javax.swing.JLabel();
        jComboBox_Modo = new javax.swing.JComboBox<>();
        jLabel_Dificultad = new javax.swing.JLabel();
        jComboBox_Dificultad = new javax.swing.JComboBox<>();
        jButton_Cerrar = new javax.swing.JButton();
        jButton_Mostrar_datos = new javax.swing.JButton();
        jLabel_Ventana_Actual = new javax.swing.JLabel();
        jComboBox_Filtro = new javax.swing.JComboBox<>();
        jLabel_Filtro = new javax.swing.JLabel();
        jButton_Volver = new javax.swing.JButton();
        JFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_modo.setFont(new java.awt.Font("Digital Dare", 1, 36)); // NOI18N
        jLabel_modo.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_modo.setText("MODO");
        getContentPane().add(jLabel_modo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 170, 30));

        jComboBox_Modo.setFont(new java.awt.Font("Digital Dare", 0, 14)); // NOI18N
        jComboBox_Modo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ARCADE", "TIME TRIAL", "STRINGS" }));
        getContentPane().add(jComboBox_Modo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 300, 40));

        jLabel_Dificultad.setFont(new java.awt.Font("Digital Dare", 1, 36)); // NOI18N
        jLabel_Dificultad.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Dificultad.setText("DIFICULTAD");
        getContentPane().add(jLabel_Dificultad, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, -1, -1));

        jComboBox_Dificultad.setFont(new java.awt.Font("Digital Dare", 0, 14)); // NOI18N
        jComboBox_Dificultad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FACIL", "NORMAL", "DIFICIL" }));
        jComboBox_Dificultad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_DificultadActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox_Dificultad, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, 300, 40));

        jButton_Cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Icon.png"))); // NOI18N
        jButton_Cerrar.setToolTipText("Cierra la aplicación ");
        jButton_Cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CerrarActionPerformed(evt);
            }
        });
        jButton_Cerrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton_CerrarKeyPressed(evt);
            }
        });
        getContentPane().add(jButton_Cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 10, 40, 20));

        jButton_Mostrar_datos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton_mostrar_datos.png"))); // NOI18N
        getContentPane().add(jButton_Mostrar_datos, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 390, 170, 50));

        jLabel_Ventana_Actual.setFont(new java.awt.Font("Digital Dare", 1, 24)); // NOI18N
        jLabel_Ventana_Actual.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Ventana_Actual.setText("RANDOM.MATHS/RANKING");
        getContentPane().add(jLabel_Ventana_Actual, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 380, -1));

        jComboBox_Filtro.setFont(new java.awt.Font("Digital Dare", 0, 14)); // NOI18N
        jComboBox_Filtro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SEMANAL", "MENSUAL", "TODOS LOS TIEMPOS" }));
        getContentPane().add(jComboBox_Filtro, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 220, 300, 40));

        jLabel_Filtro.setFont(new java.awt.Font("Digital Dare", 1, 36)); // NOI18N
        jLabel_Filtro.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Filtro.setText("Filtro\n");
        getContentPane().add(jLabel_Filtro, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 170, -1, -1));

        jButton_Volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/volver_small.png"))); // NOI18N
        getContentPane().add(jButton_Volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 480, 170, 50));

        JFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Fondo.png"))); // NOI18N
        getContentPane().add(JFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 780));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox_DificultadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_DificultadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_DificultadActionPerformed

    private void jButton_CerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CerrarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton_CerrarActionPerformed

    private void jButton_CerrarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton_CerrarKeyPressed

        if(evt.getKeyCode() == KeyEvent.VK_ESCAPE){

            System.exit(0);

        }
    }//GEN-LAST:event_jButton_CerrarKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana_Ranking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana_Ranking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana_Ranking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana_Ranking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana_Ranking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JFondo;
    private javax.swing.JButton jButton_Cerrar;
    private javax.swing.JButton jButton_Mostrar_datos;
    public javax.swing.JButton jButton_Volver;
    public javax.swing.JComboBox<String> jComboBox_Dificultad;
    public javax.swing.JComboBox<String> jComboBox_Filtro;
    public javax.swing.JComboBox<String> jComboBox_Modo;
    private javax.swing.JLabel jLabel_Dificultad;
    private javax.swing.JLabel jLabel_Filtro;
    private javax.swing.JLabel jLabel_Ventana_Actual;
    private javax.swing.JLabel jLabel_modo;
    // End of variables declaration//GEN-END:variables
}
