/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_Vista;

import com.sun.glass.events.KeyEvent;

/**
 *
 * @author Pedro
 */
public class Ventana_Seleccion extends javax.swing.JFrame {

    /**
     * Creates new form Ventana_Eleccion
     */
    public Ventana_Seleccion() {
        initComponents();
        this.setLocationRelativeTo(null); // Obliga a que la ventana se abra en el centro de la pantalla
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_Cerrar = new javax.swing.JButton();
        jLabel_Ventana_Actual = new javax.swing.JLabel();
        jLabel_modo = new javax.swing.JLabel();
        jComboBox_Modo = new javax.swing.JComboBox<>();
        jLabel_Dificultad = new javax.swing.JLabel();
        jComboBox_Dificultad = new javax.swing.JComboBox<>();
        jButton_Jugar = new javax.swing.JButton();
        jLabel_Preferencias = new javax.swing.JLabel();
        jCheckBox_sumas = new javax.swing.JCheckBox();
        jCheckBox_restas = new javax.swing.JCheckBox();
        jCheckBox_mult = new javax.swing.JCheckBox();
        jCheckBox_div = new javax.swing.JCheckBox();
        jCheckBox_porcentaje = new javax.swing.JCheckBox();
        jLabel_incluir = new javax.swing.JLabel();
        jLabel_Digitos = new javax.swing.JLabel();
        jTextField_Sumas = new javax.swing.JTextField();
        jTextField_Restas = new javax.swing.JTextField();
        jTextField_Mult = new javax.swing.JTextField();
        jTextField_Div = new javax.swing.JTextField();
        jTextField_Porcentaje = new javax.swing.JTextField();
        jLabel_modo_Preferencias = new javax.swing.JLabel();
        jComboBox_Modo_Preferencias = new javax.swing.JComboBox<>();
        jLabel_Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton_Cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Icon.png"))); // NOI18N
        jButton_Cerrar.setToolTipText("Cierra la aplicación ");
        jButton_Cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CerrarActionPerformed(evt);
            }
        });
        jButton_Cerrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton_CerrarKeyPressed(evt);
            }
        });
        getContentPane().add(jButton_Cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 10, 40, 20));

        jLabel_Ventana_Actual.setFont(new java.awt.Font("Digital Dare", 1, 24)); // NOI18N
        jLabel_Ventana_Actual.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Ventana_Actual.setText("RANDOM.MATHS/SELECCION de MODO");
        getContentPane().add(jLabel_Ventana_Actual, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 570, -1));

        jLabel_modo.setFont(new java.awt.Font("Digital Dare", 1, 36)); // NOI18N
        jLabel_modo.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_modo.setText("MODO");
        getContentPane().add(jLabel_modo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 130, 30));

        jComboBox_Modo.setFont(new java.awt.Font("Digital Dare", 0, 18)); // NOI18N
        jComboBox_Modo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ARCADE", "TIME TRIAL", "STRINGS", "CUSTOM" }));
        jComboBox_Modo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_ModoActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox_Modo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 300, 40));

        jLabel_Dificultad.setFont(new java.awt.Font("Digital Dare", 1, 36)); // NOI18N
        jLabel_Dificultad.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Dificultad.setText("DIFICULTAD");
        getContentPane().add(jLabel_Dificultad, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 140, -1, -1));

        jComboBox_Dificultad.setFont(new java.awt.Font("Digital Dare", 0, 18)); // NOI18N
        jComboBox_Dificultad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FACIL", "NORMAL", "DIFICIL" }));
        jComboBox_Dificultad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_DificultadActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox_Dificultad, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 200, 300, 40));

        jButton_Jugar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton_jugar.png"))); // NOI18N
        jButton_Jugar.setToolTipText("Juega una partida en uno de los 4 modos disponibles: Arcade, Time Trial, Strings o Custom.");
        getContentPane().add(jButton_Jugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 570, 350, 50));

        jLabel_Preferencias.setFont(new java.awt.Font("Digital Dare", 1, 36)); // NOI18N
        jLabel_Preferencias.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Preferencias.setText("Preferencias (SOLO MODO CUSTOM)");
        getContentPane().add(jLabel_Preferencias, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 900, 30));

        jCheckBox_sumas.setFont(new java.awt.Font("Digital Dare", 0, 18)); // NOI18N
        jCheckBox_sumas.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox_sumas.setText("Sumas");
        getContentPane().add(jCheckBox_sumas, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 400, 110, 30));

        jCheckBox_restas.setFont(new java.awt.Font("Digital Dare", 0, 18)); // NOI18N
        jCheckBox_restas.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox_restas.setText("RESTAS");
        jCheckBox_restas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_restasActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox_restas, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 400, 110, 30));

        jCheckBox_mult.setFont(new java.awt.Font("Digital Dare", 0, 14)); // NOI18N
        jCheckBox_mult.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox_mult.setText("MULTIPLICACIONES");
        jCheckBox_mult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_multActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox_mult, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 400, 190, 30));

        jCheckBox_div.setFont(new java.awt.Font("Digital Dare", 0, 18)); // NOI18N
        jCheckBox_div.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox_div.setText("DIVISIONES");
        jCheckBox_div.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_divActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox_div, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 400, 160, 30));

        jCheckBox_porcentaje.setFont(new java.awt.Font("Digital Dare", 0, 14)); // NOI18N
        jCheckBox_porcentaje.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox_porcentaje.setText("PORCENTAJES");
        jCheckBox_porcentaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_porcentajeActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox_porcentaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 400, 160, 30));

        jLabel_incluir.setFont(new java.awt.Font("Digital Dare", 0, 18)); // NOI18N
        jLabel_incluir.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_incluir.setText("INCLUIR:");
        getContentPane().add(jLabel_incluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 400, -1, -1));

        jLabel_Digitos.setFont(new java.awt.Font("Digital Dare", 0, 18)); // NOI18N
        jLabel_Digitos.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Digitos.setText("Digitos:");
        getContentPane().add(jLabel_Digitos, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 450, -1, -1));

        jTextField_Sumas.setFont(new java.awt.Font("Digital Dare", 1, 18)); // NOI18N
        jTextField_Sumas.setToolTipText("");
        jTextField_Sumas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_SumasActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_Sumas, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 450, 110, 30));

        jTextField_Restas.setFont(new java.awt.Font("Digital Dare", 1, 18)); // NOI18N
        jTextField_Restas.setToolTipText("");
        getContentPane().add(jTextField_Restas, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 450, 110, 30));

        jTextField_Mult.setFont(new java.awt.Font("Digital Dare", 1, 18)); // NOI18N
        jTextField_Mult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_MultActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_Mult, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 450, 110, 30));

        jTextField_Div.setFont(new java.awt.Font("Digital Dare", 1, 18)); // NOI18N
        jTextField_Div.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_DivActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_Div, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 450, 110, 30));

        jTextField_Porcentaje.setFont(new java.awt.Font("Digital Dare", 1, 18)); // NOI18N
        getContentPane().add(jTextField_Porcentaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 450, 110, 30));

        jLabel_modo_Preferencias.setFont(new java.awt.Font("Digital Dare", 1, 18)); // NOI18N
        jLabel_modo_Preferencias.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_modo_Preferencias.setText("MODO:");
        getContentPane().add(jLabel_modo_Preferencias, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 80, 30));

        jComboBox_Modo_Preferencias.setFont(new java.awt.Font("Digital Dare", 0, 14)); // NOI18N
        jComboBox_Modo_Preferencias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ARCADE", "TIME TRIAL", "STRINGS" }));
        jComboBox_Modo_Preferencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_Modo_PreferenciasActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox_Modo_Preferencias, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, 110, 40));

        jLabel_Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Fondo.png"))); // NOI18N
        getContentPane().add(jLabel_Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 780));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_CerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CerrarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton_CerrarActionPerformed

    private void jButton_CerrarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton_CerrarKeyPressed

        if(evt.getKeyCode() == KeyEvent.VK_ESCAPE){

            System.exit(0);

        }
    }//GEN-LAST:event_jButton_CerrarKeyPressed

    private void jComboBox_ModoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_ModoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_ModoActionPerformed

    private void jComboBox_DificultadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_DificultadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_DificultadActionPerformed

    private void jCheckBox_restasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_restasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox_restasActionPerformed

    private void jCheckBox_multActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_multActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox_multActionPerformed

    private void jCheckBox_divActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_divActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox_divActionPerformed

    private void jCheckBox_porcentajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_porcentajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox_porcentajeActionPerformed

    private void jTextField_SumasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_SumasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_SumasActionPerformed

    private void jTextField_DivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_DivActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_DivActionPerformed

    private void jTextField_MultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_MultActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_MultActionPerformed

    private void jComboBox_Modo_PreferenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_Modo_PreferenciasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_Modo_PreferenciasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana_Seleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana_Seleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana_Seleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana_Seleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana_Seleccion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Cerrar;
    private javax.swing.JButton jButton_Jugar;
    private javax.swing.JCheckBox jCheckBox_div;
    private javax.swing.JCheckBox jCheckBox_mult;
    private javax.swing.JCheckBox jCheckBox_porcentaje;
    private javax.swing.JCheckBox jCheckBox_restas;
    private javax.swing.JCheckBox jCheckBox_sumas;
    private javax.swing.JComboBox<String> jComboBox_Dificultad;
    private javax.swing.JComboBox<String> jComboBox_Modo;
    private javax.swing.JComboBox<String> jComboBox_Modo_Preferencias;
    private javax.swing.JLabel jLabel_Dificultad;
    private javax.swing.JLabel jLabel_Digitos;
    private javax.swing.JLabel jLabel_Fondo;
    private javax.swing.JLabel jLabel_Preferencias;
    private javax.swing.JLabel jLabel_Ventana_Actual;
    private javax.swing.JLabel jLabel_incluir;
    private javax.swing.JLabel jLabel_modo;
    private javax.swing.JLabel jLabel_modo_Preferencias;
    private javax.swing.JTextField jTextField_Div;
    private javax.swing.JTextField jTextField_Mult;
    private javax.swing.JTextField jTextField_Porcentaje;
    private javax.swing.JTextField jTextField_Restas;
    private javax.swing.JTextField jTextField_Sumas;
    // End of variables declaration//GEN-END:variables
}
