/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_Vista;

import com.sun.glass.events.KeyEvent;

/**
 *
 * @author Pedro
 */
public class Ventana_Ranking extends javax.swing.JFrame {

    /**
     * Creates new form Ventana_Ranking
     */
    public Ventana_Ranking() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_modo = new javax.swing.JLabel();
        jComboBox_Modo = new javax.swing.JComboBox<>();
        jLabel_Dificultad = new javax.swing.JLabel();
        jComboBox_Dificultad = new javax.swing.JComboBox<>();
        jButton_Cerrar = new javax.swing.JButton();
        jButton_Consultar = new javax.swing.JButton();
        jLabel_Ventana_Actual = new javax.swing.JLabel();
        jButton_Volver = new javax.swing.JButton();
        jLabel_LogAs = new javax.swing.JLabel();
        Tabla = new javax.swing.JScrollPane();
        Tabla_Ranking = new javax.swing.JTable();
        JFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_modo.setFont(new java.awt.Font("Digital Dare", 1, 36)); // NOI18N
        jLabel_modo.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_modo.setText("MODO");
        getContentPane().add(jLabel_modo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 170, 30));

        jComboBox_Modo.setFont(new java.awt.Font("Digital Dare", 0, 14)); // NOI18N
        getContentPane().add(jComboBox_Modo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 300, 40));

        jLabel_Dificultad.setFont(new java.awt.Font("Digital Dare", 1, 36)); // NOI18N
        jLabel_Dificultad.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Dificultad.setText("DIFICULTAD");
        getContentPane().add(jLabel_Dificultad, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 170, -1, -1));

        jComboBox_Dificultad.setFont(new java.awt.Font("Digital Dare", 0, 14)); // NOI18N
        jComboBox_Dificultad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_DificultadActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox_Dificultad, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 220, 300, 40));

        jButton_Cerrar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Equipo\\Documents\\NetBeansProjects\\proyecto_programacion\\src\\imagenes\\Icon.png")); // NOI18N
        jButton_Cerrar.setToolTipText("Cierra la aplicación ");
        jButton_Cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CerrarActionPerformed(evt);
            }
        });
        jButton_Cerrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton_CerrarKeyPressed(evt);
            }
        });
        getContentPane().add(jButton_Cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 10, 40, 20));

        jButton_Consultar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Equipo\\Documents\\NetBeansProjects\\proyecto_programacion\\src\\imagenes\\boton_consultar.png")); // NOI18N
        getContentPane().add(jButton_Consultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 600, 240, 75));

        jLabel_Ventana_Actual.setFont(new java.awt.Font("Digital Dare", 1, 24)); // NOI18N
        jLabel_Ventana_Actual.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Ventana_Actual.setText("RANDOM.MATHS/RANKING");
        getContentPane().add(jLabel_Ventana_Actual, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 380, -1));

        jButton_Volver.setIcon(new javax.swing.ImageIcon("C:\\Users\\Equipo\\Documents\\NetBeansProjects\\proyecto_programacion\\src\\imagenes\\boton_volver.png")); // NOI18N
        jButton_Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_VolverActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 600, 240, 75));

        jLabel_LogAs.setFont(new java.awt.Font("Digital Dare", 1, 24)); // NOI18N
        jLabel_LogAs.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_LogAs.setText("LOG: ");
        getContentPane().add(jLabel_LogAs, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 740, 460, -1));

        Tabla_Ranking.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Tabla_Ranking.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Tabla.setViewportView(Tabla_Ranking);

        getContentPane().add(Tabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 740, 190));

        JFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Fondo.png"))); // NOI18N
        getContentPane().add(JFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 780));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox_DificultadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_DificultadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_DificultadActionPerformed

    private void jButton_CerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CerrarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton_CerrarActionPerformed

    private void jButton_CerrarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton_CerrarKeyPressed

        if(evt.getKeyCode() == KeyEvent.VK_ESCAPE){

            System.exit(0);

        }
    }//GEN-LAST:event_jButton_CerrarKeyPressed

    private void jButton_VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_VolverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_VolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana_Ranking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana_Ranking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana_Ranking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana_Ranking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana_Ranking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JFondo;
    private javax.swing.JScrollPane Tabla;
    public javax.swing.JTable Tabla_Ranking;
    public javax.swing.JButton jButton_Cerrar;
    public javax.swing.JButton jButton_Consultar;
    public javax.swing.JButton jButton_Volver;
    public javax.swing.JComboBox<String> jComboBox_Dificultad;
    public javax.swing.JComboBox<String> jComboBox_Modo;
    private javax.swing.JLabel jLabel_Dificultad;
    public javax.swing.JLabel jLabel_LogAs;
    private javax.swing.JLabel jLabel_Ventana_Actual;
    private javax.swing.JLabel jLabel_modo;
    // End of variables declaration//GEN-END:variables
}
